name: flask app for random fruit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v1
      with: 
        python-version: 3.8
    - name: install dependency
      run: make install
    - name: lint with pylint
      run: make lint
    - name: format
      run: make format
    - name: test
      run: make test

